version: '3'

tasks:
  build:
    desc: Build the docker image
    cmds:
      - docker build -t inqora-grpc-test -f Dockerfile ../..

  start:
    desc: Start the service in development mode
    cmds:
      - npm run dev

  up:
    desc: Start the service in a docker container
    cmds:
      - docker run inqora-grpc-test

  stop:
    desc: Stop the service (docker)
    cmds:
      - docker stop inqora-grpc-test || true
      - docker rm inqora-grpc-test || true
